/**
 * @emf-webapp/core — MTL File Manager
 *
 * Manages file outputs generated by MTL templates.
 * Supports:
 * - Open modes: overwrite (default), append, create (only if new)
 * - Protected areas: preserve user code between regenerations
 * - Encoding metadata per file
 * - Subdirectory paths (auto-created in output)
 */

export interface GeneratedFile {
  name: string;
  content: string;
  encoding: string;
  /** Whether this file was skipped (create mode, already existed) */
  skipped?: boolean;
}

export class MTLFileManager {
  private files: Map<string, { content: string; encoding: string }> = new Map();

  /**
   * Storage for protected areas keyed by their ID.
   * On regeneration, existing content is preserved and reinserted.
   */
  protectedAreas: Map<string, string> = new Map();

  /**
   * Previous generation output — used to detect "lost files" and
   * preserve protected areas across regenerations.
   */
  private previousOutput: Map<string, string> = new Map();

  /**
   * Files that were skipped due to 'create' mode (already existed).
   */
  private skippedFiles: Set<string> = new Set();

  /**
   * Load previous generation output for protected area preservation
   * and lost file detection.
   */
  loadPreviousOutput(files: Array<{ name: string; content: string }>): void {
    this.previousOutput.clear();
    for (const f of files) {
      this.previousOutput.set(f.name, f.content);
      // Extract protected areas from previous output
      this.extractProtectedAreas(f.content);
    }
  }

  /**
   * Add a generated file output with mode support.
   * @param name - File path (can include subdirectories like 'src/model/Person.java')
   * @param content - Generated content
   * @param openMode - 'overwrite' (default), 'append', 'create'
   * @param encoding - File encoding (default: 'UTF-8')
   */
  addFile(name: string, content: string, openMode: string = 'overwrite', encoding: string = 'UTF-8'): void {
    const normalizedMode = this.normalizeOpenMode(openMode);

    switch (normalizedMode) {
      case 'append':
        if (this.files.has(name)) {
          const existing = this.files.get(name)!;
          this.files.set(name, { content: existing.content + content, encoding });
        } else {
          // Append to previous output if exists
          const prev = this.previousOutput.get(name) ?? '';
          this.files.set(name, { content: prev + content, encoding });
        }
        break;

      case 'create':
        // Only generate if file doesn't already exist in previous output
        if (this.previousOutput.has(name)) {
          this.skippedFiles.add(name);
          return;
        }
        this.files.set(name, { content, encoding });
        break;

      case 'overwrite':
      default:
        // Merge protected areas from previous content
        const previousContent = this.previousOutput.get(name);
        if (previousContent) {
          content = this.mergeProtectedAreas(content, previousContent);
        }
        this.files.set(name, { content, encoding });
        break;
    }
  }

  /**
   * Get all generated files as an array.
   */
  getFiles(): GeneratedFile[] {
    const result: GeneratedFile[] = [];
    this.files.forEach(({ content, encoding }, name) => {
      result.push({ name, content, encoding });
    });
    return result;
  }

  /**
   * Get files that existed in previous output but are no longer generated.
   */
  getLostFiles(): string[] {
    const currentNames = new Set(Array.from(this.files.keys()));
    const lost: string[] = [];
    for (const name of Array.from(this.previousOutput.keys())) {
      if (!currentNames.has(name) && !this.skippedFiles.has(name)) {
        lost.push(name);
      }
    }
    return lost;
  }

  /**
   * Get generation statistics.
   */
  getStats(): { generated: number; skipped: number; lost: number } {
    return {
      generated: this.files.size,
      skipped: this.skippedFiles.size,
      lost: this.getLostFiles().length,
    };
  }

  /**
   * Capture the content of a protected area during generation.
   */
  captureProtected(id: string, content: string): void {
    this.protectedAreas.set(id, content);
  }

  /**
   * Restore previously captured protected area content.
   * Returns the preserved user code if it exists, empty string otherwise.
   */
  restoreProtected(id: string, _existingContent: string): string {
    return this.protectedAreas.get(id) ?? '';
  }

  // ─── Private helpers ─────────────────────────────────────────────────────────

  /**
   * Normalize open mode from Acceleo syntax.
   * Acceleo uses: 'overwrite'|'true' (overwrite), 'false' (append), 'create'
   */
  private normalizeOpenMode(mode: string): 'overwrite' | 'append' | 'create' {
    const m = mode.toLowerCase().trim();
    if (m === 'append' || m === 'false') return 'append';
    if (m === 'create') return 'create';
    return 'overwrite'; // 'overwrite', 'true', or default
  }

  /**
   * Extract protected areas from file content using standard markers.
   * Supports multiple comment styles.
   */
  private extractProtectedAreas(content: string): void {
    // Match patterns like:
    // // Start of user code ID
    // ... content ...
    // // End of user code
    const patterns = [
      /\/\/\s*Start of user code\s+(\S+)\s*\n([\s\S]*?)\/\/\s*End of user code/g,
      /#\s*Start of user code\s+(\S+)\s*\n([\s\S]*?)#\s*End of user code/g,
      /<!--\s*Start of user code\s+(\S+)\s*-->\s*\n([\s\S]*?)<!--\s*End of user code\s*-->/g,
    ];

    for (const pattern of patterns) {
      let match: RegExpExecArray | null;
      while ((match = pattern.exec(content)) !== null) {
        const id = match[1];
        const body = match[2];
        if (id && body !== undefined) {
          this.protectedAreas.set(id, body);
        }
      }
    }
  }

  /**
   * Merge protected areas from previous content into newly generated content.
   * Replaces the default body of protected areas with previously saved user code.
   */
  private mergeProtectedAreas(newContent: string, previousContent: string): string {
    // First extract from previous
    const prevAreas = new Map<string, string>();
    const patterns = [
      { regex: /\/\/\s*Start of user code\s+(\S+)\s*\n([\s\S]*?)\/\/\s*End of user code/g, start: '// Start of user code', end: '// End of user code' },
      { regex: /#\s*Start of user code\s+(\S+)\s*\n([\s\S]*?)#\s*End of user code/g, start: '# Start of user code', end: '# End of user code' },
      { regex: /<!--\s*Start of user code\s+(\S+)\s*-->\s*\n([\s\S]*?)<!--\s*End of user code\s*-->/g, start: '<!-- Start of user code', end: '<!-- End of user code -->' },
    ];

    for (const { regex } of patterns) {
      let match: RegExpExecArray | null;
      while ((match = regex.exec(previousContent)) !== null) {
        if (match[1] && match[2]) {
          prevAreas.set(match[1], match[2]);
        }
      }
    }

    if (prevAreas.size === 0) return newContent;

    // Replace in new content
    let result = newContent;
    for (const { regex } of patterns) {
      // Reset regex
      regex.lastIndex = 0;
      result = result.replace(regex, (fullMatch, id, _body) => {
        const preserved = prevAreas.get(id);
        if (preserved !== undefined) {
          // Replace body with preserved content, keep markers
          return fullMatch.replace(_body, preserved);
        }
        return fullMatch;
      });
    }

    return result;
  }
}
