/**
 * @emf-webapp/core — MTL File Manager
 *
 * Manages file outputs generated by MTL templates and
 * handles protected area storage for regeneration.
 */

export class MTLFileManager {
  private files: Map<string, string> = new Map();

  /**
   * Storage for protected areas keyed by their ID.
   * On regeneration, existing content is preserved and reinserted.
   */
  protectedAreas: Map<string, string> = new Map();

  /**
   * Add a generated file output.
   */
  addFile(name: string, content: string): void {
    // If the file already exists, append or replace based on use case
    if (this.files.has(name)) {
      this.files.set(name, this.files.get(name)! + '\n' + content);
    } else {
      this.files.set(name, content);
    }
  }

  /**
   * Get all generated files as an array of { name, content } objects.
   */
  getFiles(): Array<{ name: string; content: string }> {
    const result: Array<{ name: string; content: string }> = [];
    for (const [name, content] of this.files) {
      result.push({ name, content });
    }
    return result;
  }

  /**
   * Capture the content of a protected area during generation.
   */
  captureProtected(id: string, content: string): void {
    this.protectedAreas.set(id, content);
  }

  /**
   * Restore previously captured protected area content.
   * If no content exists for this ID, returns the empty string
   * (meaning fresh generation should proceed).
   *
   * @param id - Protected area identifier
   * @param existingContent - Current file content (unused in simple storage, kept for API compatibility)
   * @returns Previously captured content or empty string
   */
  restoreProtected(id: string, _existingContent: string): string {
    return this.protectedAreas.get(id) ?? '';
  }
}
